USE sakila;
GO

--using EOMONTH
SELECT EOMONTH(GETDATE()) AS [End of this month],
    EOMONTH(GETDATE(),1) AS [End of next month],
    EOMONTH(GETDATE(),-1) AS [End of last month],
    EOMONTH('2020-01-01') AS [End of January];

--using DATEFROMPARTS
SELECT DATEFROMPARTS(2012, 3, 10) AS DATEFROMPARTS,
    TIMEFROMPARTS(12, 10, 32, 0, 0) AS TIMEFROMPARTS,
    DATETIME2FROMPARTS (2012, 3, 10, 12, 10, 32, 0, 0) AS DATETIME2FROMPARTS;
