SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[address](
	[AdressId] [int] IDENTITY(1,1) NOT NULL,
	[StreetAddress] [nvarchar](200) NULL,
	[ZipCode] [int] NULL,
	[City] [nvarchar](200) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[address] ADD  CONSTRAINT [PK_address] PRIMARY KEY CLUSTERED 
(
	[AdressId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
